name: cd

on:
  push:
    branches: [main]

jobs:
  Tests:        # الاسم اللي الموقع ميت عليه
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Tests              # كررنا الاسم هون كمان للتأكيد
        run: npm test

      - name: Deploy             # خطوة النشر بداخل نفس الـ Job
        run: npm run build
