name: CD

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # الخطوة 1: المصادقة مع جوجل سحاب باستخدام السر المخزن في GitHub
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # الخطوة 2: إعداد أدوات gcloud CLI في بيئة العمل
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      # الخطوة 3: بناء صورة Docker ورفعها إلى Artifact Registry
      - name: 'Build and Push to Artifact Registry'
        run: |
          gcloud builds submit --tag us-central1-docker.pkg.dev/notely-490519/notely-ar-repo/notely:latest .

      - name: 'Deploy to Cloud Run'
        run: |
          gcloud run deploy notely \
            --image us-central1-docker.pkg.dev/notely-490519/notely-ar-repo/notely:latest \
            --region us-central1 \
            --allow-unauthenticated \
            --project notely-490519 \
            --max-instances=4
